/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./components/layout/AppLayout.vue')['default']
    DemandCard: typeof import('./components/common/DemandCard.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    Footer: typeof import('./components/layout/Footer.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    OrderCard: typeof import('./components/common/OrderCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    SkillCard: typeof import('./components/common/SkillCard.vue')['default']
    TimeSlotPicker: typeof import('./components/common/TimeSlotPicker.vue')['default']
    TrustBadge: typeof import('./components/common/TrustBadge.vue')['default']
    UserAvatar: typeof import('./components/common/UserAvatar.vue')['default']
    VerifyCode: typeof import('./components/common/VerifyCode.vue')['default']
  }
}
