# =============================================================================
# 合并 database/migration/ 下的所有 SQL 脚本为 docker/mysql/init.sql
# 使用方法: .\scripts\build-init-sql.ps1
# =============================================================================

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
$MigrationDir = Join-Path $ProjectRoot "database\migration"
$OutputFile = Join-Path $ProjectRoot "docker\mysql\init.sql"

if (-not (Test-Path $MigrationDir)) {
    Write-Error "Migration directory not found: $MigrationDir"
    exit 1
}

$OutputDir = Split-Path -Parent $OutputFile
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

$header = @"
-- ============================================================================
-- DaBaShou Database Initialization Script
-- Auto-generated from database/migration/ on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
-- DO NOT EDIT THIS FILE DIRECTLY - modify migration scripts instead
-- ============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

"@

$footer = @"

SET FOREIGN_KEY_CHECKS = 1;
"@

$migrationFiles = Get-ChildItem -Path $MigrationDir -Filter "V*.sql" | Sort-Object Name

if ($migrationFiles.Count -eq 0) {
    Write-Error "No migration files found in $MigrationDir"
    exit 1
}

$content = $header
foreach ($file in $migrationFiles) {
    $content += "`n-- ============================================================================$n"
    $content += "-- Source: $($file.Name)`n"
    $content += "-- ============================================================================$n`n"
    $content += Get-Content $file.FullName -Raw -Encoding UTF8
    $content += "`n"
}
$content += $footer

[System.IO.File]::WriteAllText($OutputFile, $content, [System.Text.Encoding]::UTF8)

Write-Host "Generated: $OutputFile" -ForegroundColor Green
Write-Host "Merged $($migrationFiles.Count) migration files:" -ForegroundColor Cyan
$migrationFiles | ForEach-Object { Write-Host "  - $($_.Name)" -ForegroundColor DarkGray }
